WORDS = [
    "Do it!", "Go for it.", "Totally.", "Yes, definitely.", "All good.", "100%.", "For sure.", "Perfect.", 
    "Absolutely.", "Full send.", "Make it happen.", "Approved.", "Heck yes.", "Indeed.", "Spot on.", 
    "Green light.", "Execute.", "By all means.", "Affirmative.", "You bet.", "Right on.", "Certainly.", 
    "Definitely.", "Of course.", "Without a doubt.", "Go ahead.", "Proceed.", "Let's roll.", "Fire away.", 
    "Send it.", "Jackpot.", "Precisely.", "Correct.", "Exactly.", "You got it.", "Sounds good.", 
    "Count me in.", "I'm down.", "All systems go.", "Bet.", "Sure thing.", "Positive.", "Validated.", 
    "Confirmed.", "Go, go, go!", "Clear for takeoff.", "Non-negotiable yes.", "Believe it.", "Most definitely.", 
    "Naturally.", "Undoubtedly.", "A-okay.", "Roger that.", "Copy that.", "Wilco.", "Understood.", 
    "Accepted.", "Right away.", "Consider it done.", "Don't mind if I do.", "Ready when you are.", 
    "Thumbs up.", "Golden.", "Flawless.", "Solid.", "Excellent.", "Superb.", "Outstanding.", 
    "Phenomenal.", "Brilliant.", "Great idea.", "Winner.", "Bravo.", "Encore.", "Keep going.", 
    "Full throttle.", "No brainer.", "Obviously.", "Plainly.", "Clearly.", "Yes, please.", "Fair enough.", 
    "Check.", "Righto.", "Aye aye.", "Indubitably.", "Beyond a doubt.", "True.", "Word.", "Facts.", 
    "No cap.", "Legit.", "Vouch.", "Permitted.", "Authorized.", "Go time.", "Blast off.", "Ship it.", 
    "Lock it in.", "Do it now.", "Don't hesitate.", "Press play.", "Engage.", "Ignite.", "Commence.", 
    "Start.", "Initiate.", "Trigger.", "Activate.", "Enable.", "Set.", "Ready.", "Steady.", "Punch it.", 
    "Hit it.", "Take the leap.", "Dive in.", "Jump in.", "Step up.", "Move forward.", "Advance.", 
    "Progression.", "Onwards.", "Upwards.", "Sky's the limit.", "Win-win.", "Aced it.", "Top notch.", 
    "First class.", "World class.", "High five.", "Cheers.", "Toast.", "Celebrate.", "Keep it up.", 
    "Stay the course.", "Maintain.", "Sustain.", "Thrive.", "Flourish.", "Bloom.", "Grow.", "Expand.", 
    "Reach out.", "Touch base.", "Connect.", "Sync.", "Align.", "Match.", "Fit.", "Suitable.", 
    "Appropriate.", "Relevant.", "Correctamundo.", "Right on the money.", "Bullseye.", "Target hit.", 
    "Success.", "Victory.", "Triumph.", "Glory.", "Honor.", "Respect.", "Salute.", "Hail.", "Praise.", 
    "Applaud.", "Commend.", "Support.", "Endorse.", "Back it.", "Fund it.", "Finance.", "Sponsor.", 
    "Patronize.", "Advocate.", "Champion.", "Promote.", "Boost.", "Lift.", "Raise.", "Elevate.", 
    "Ascend.", "Climb.", "Scale.", "Peak.", "Summit.", "Apex.", "Zenith.", "Pinnacle.", "Climax.", 
    "Crescendo.", "Overture.", "Prelude.", "Intro.", "Start-up.", "Launch.", "Unveil.", "Reveal.", 
    "Showcase.", "Display.", "Exhibit.", "Manifest.", "Realize.", "Actualize.", "Fulfill.", "Complete.", 
    "Finish.", "Conclude.", "Finalize.", "Seal the deal.", "Sign off.", "Stamp.", "Certify.", "Attest.", 
    "Witness.", "Verify.", "Audit.", "Review.", "Pass.", "Cleared.", "Secure.", "Safe.", "Sound.", 
    "Stable.", "Reliable.", "Trustworthy.", "Honest.", "True blue.", "Genuine.", "Authentic.", 
    "Real deal.", "Pure.", "Refined.", "Polished.", "Shiny.", "Bright.", "Radiant.", "Glow.", "Light.", 
    "Sunlight.", "Sunshine.", "Daybreak.", "Dawn.", "New day.", "Fresh start.", "Reset.", "Renew.", 
    "Restore.", "Revive.", "Refresh.", "Recharge.", "Energize.", "Power up.", "Level up.", "Upgrade.",
    "No way.", "Don't do it.", "Hard pass.", "Not a good idea.", "Nope.", "Stop.", "Bad move.", 
    "Forget it.", "Abort mission.", "Negative.", "No chance.", "Avoid.", "Walk away.", "Not feeling it.", 
    "Stay back.", "Cease and desist.", "Hold your horses.", "Wait a minute.", "No go.", "Denied.", 
    "Rejected.", "Vetoed.", "Not on my watch.", "Never.", "Zero chance.", "Absolutely not.", 
    "Under no circumstances.", "Forget about it.", "Not happening.", "Dream on.", "Fat chance.", 
    "Not likely.", "Think again.", "Don't bother.", "Highly unlikely.", "Hard no.", "Pass.", 
    "I'll pass.", "Negative ghostrider.", "Disapproved.", "Invalid.", "Forbidden.", "Prohibited.", 
    "Halt.", "Stand down.", "Back off.", "Cut it out.", "End it.", "No thanks.", "I'm good.", 
    "Not today.", "Maybe another time.", "Nah.", "Hardly.", "Scarcely.", "No way, Jose.", 
    "Out of the question.", "Pipe down.", "Non-starter.", "Dead on arrival.", "Red light.", 
    "Danger.", "Hazardous.", "Not wise.", "Ill-advised.", "Risky.", "Unsafe.", "Terrible idea.", 
    "Big mistake.", "Wrong way.", "Turn back.", "Don't even start.", "Quit it.", "Give it a rest.", 
    "No sir.", "No ma'am.", "Uhm, no.", "False.", "Incorrect.", "Error.", "System failure.", 
    "Nix that.", "Scratch that.", "Delete.", "Cancel.", "Void.", "Nullified.", "Blocked.", 
    "Improper.", "Unacceptable.", "Inadequate.", "Poor choice.", "Do not.", "Refrain.", "Desist.", 
    "Pause.", "Slow down.", "Warning.", "Caution.", "Alert.", "Red flag.", "Siren.", "Alarm.", 
    "Emergency.", "Crisis.", "Disaster.", "Catastrophe.", "Failure.", "Flop.", "Dud.", "Miss.", 
    "Fail.", "Loser.", "Bottom out.", "Crash.", "Burn.", "Explode.", "Implode.", "Collapse.", 
    "Break down.", "Glitch.", "Bug.", "Fault.", "Defect.", "Flaw.", "Blemish.", "Stain.", "Taint.", 
    "Corrupt.", "Broken.", "Damaged.", "Ruined.", "Destroyed.", "Wasted.", "Useless.", "Worthless.", 
    "Pointless.", "Insignificant.", "Null.", "Zero.", "Zip.", "Nada.", "Naught.", "Nil.", 
    "None.", "Neither.", "Nor.", "Nevermore.", "Once bitten.", "Twice shy.", "Once in a blue moon.", 
    "Cold day in hell.", "When pigs fly.", "Not in a million years.", "Skip it.", "Bypass.", 
    "Ignore.", "Neglect.", "Overlook.", "Omit.", "Exclude.", "Dismiss.", "Discard.", "Dump.", 
    "Trash.", "Junk.", "Scrap.", "Waste.", "Garbage.", "Rubbish.", "Nonsense.", "Baloney.", 
    "Hogwash.", "Ridiculous.", "Absurd.", "Ludicrous.", "Preposterous.", "Insane.", "Crazy.", 
    "Madness.", "Foolish.", "Stupid.", "Dumb.", "Ignorant.", "Blind.", "Deaf.", "Silent.", 
    "Mute.", "Still.", "Quiet.", "Soft.", "Weak.", "Feeble.", "Frail.", "Fragile.", "Delicate.", 
    "Sensitive.", "Tender.", "Softie.", "Pushover.", "Easy.", "Boring.", "Dull.", "Stale.", 
    "Old.", "Ancient.", "Outdated.", "Obsolete.", "Vintage.", "Retro.", "Past it.", "Done.", 
    "Over.", "Finished.", "Gone.", "Away.", "Far.", "Distant.", "Remote.", "Hidden.", "Secret.", 
    "Private.", "Closed.", "Locked.", "Bolted.", "Shuttered.", "Barred.", "Banned.", "Exiled.", 
    "Ostracized.", "Outcast.", "Lonely.", "Solo.", "Single.", "Individual.", "Separate.", 
    "Apart.", "Divided.", "Split.", "Broken up.", "Fractured.", "Fragmented.", "Shattered.", 
    "Cracked.", "Split ends.", "Frayed.", "Worn.", "Tattered.", "Ragged.", "Rough.", "Hard.", 
    "Tough.", "Stiff.", "Rigid.", "Strict.", "Severe.", "Harsh.", "Cruel.", "Mean.", "Nasty.", 
    "Ugly.", "Gross.", "Vile.", "Evil.", "Wicked.", "Sinister.", "Dark.", "Shadowy.", "Grim."
]